/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.datagovernance;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.Pattern;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class DeepGovernanceApiTests{@Autowired MockMvc mvc;
 @Test void assetQualityIssueAndLineageFormClosedLoop()throws Exception{long source=create("UT-DG-SRC","客户源表"),target=create("UT-DG-TGT","客户主数据");addRule(target);submitAndPublish(target);mvc.perform(post("/api/governance/assets/{id}/quality-runs",target).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"runNo\":\"UT-RUN-01\",\"totalRows\":1000,\"failedRows\":200}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.result").value("FAILED")).andExpect(jsonPath("$.data.issueCreated").value(true));mvc.perform(post("/api/governance/lineage").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"organizationCode\":\"UT-DG\",\"sourceCode\":\"UT-DG-SRC\",\"targetCode\":\"UT-DG-TGT\",\"transformation\":\"标准化与去重\"}")).andExpect(status().isOk());MvcResult d=mvc.perform(get("/api/governance/dashboard").param("organizationCode","UT-DG").with(httpBasic("operator","operator123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.issues.length()").value(1)).andExpect(jsonPath("$.data.lineage.length()").value(1)).andReturn();long issue=idFrom(d.getResponse().getContentAsString(),"issues");mvc.perform(post("/api/governance/issues/{id}/assign",issue).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"assignee\":\"数据管理员\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("IN_PROGRESS"));mvc.perform(post("/api/governance/issues/{id}/resolve",issue).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"resolution\":\"完成源数据修复并重跑\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("RESOLVED"));mvc.perform(post("/api/governance/issues/{id}/close",issue).with(httpBasic("operator","operator123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("CLOSED"));}
 @Test void publishRequiresAdminAndQualityRule()throws Exception{long id=create("UT-DG-NORULE","无规则资产");mvc.perform(post("/api/governance/assets/{id}/submit",id).with(httpBasic("operator","operator123"))).andExpect(status().isOk());mvc.perform(post("/api/admin/governance/assets/{id}/publish",id).with(httpBasic("operator","operator123"))).andExpect(status().isForbidden());mvc.perform(post("/api/admin/governance/assets/{id}/publish",id).with(httpBasic("admin","admin123"))).andExpect(status().isConflict());}
 @Test void qualityRejectsImpossibleCounts()throws Exception{long id=create("UT-DG-BADCOUNT","坏数据校验");addRule(id);submitAndPublish(id);mvc.perform(post("/api/governance/assets/{id}/quality-runs",id).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"runNo\":\"UT-BAD-RUN\",\"totalRows\":10,\"failedRows\":11}")).andExpect(status().isBadRequest());}
 private long create(String code,String name)throws Exception{return idOf(mvc.perform(post("/api/governance/assets").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"organizationCode\":\"UT-DG\",\"assetCode\":\""+code+"\",\"name\":\""+name+"\",\"dataDomain\":\"客户域\",\"owner\":\"数据负责人\",\"classification\":\"内部\"}")).andExpect(status().isOk()).andReturn());}
 private void addRule(long id)throws Exception{mvc.perform(post("/api/governance/assets/{id}/rules",id).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"ruleCode\":\"COMPLETE-95\",\"ruleType\":\"COMPLETENESS\",\"expression\":\"customer_name is not null\",\"threshold\":95}")).andExpect(status().isOk());}
 private void submitAndPublish(long id)throws Exception{mvc.perform(post("/api/governance/assets/{id}/submit",id).with(httpBasic("operator","operator123"))).andExpect(status().isOk());mvc.perform(post("/api/admin/governance/assets/{id}/publish",id).with(httpBasic("admin","admin123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("PUBLISHED"));}
 private long idOf(MvcResult r)throws Exception{var m=Pattern.compile("\"id\":(\\d+)").matcher(r.getResponse().getContentAsString());Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}
 private long idFrom(String json,String section){var m=Pattern.compile("\""+section+"\":\\[\\{\"id\":(\\d+)").matcher(json);Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}
}
